services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: sitedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    restart: always

volumes:
  postgres_data:
