version: '3'
services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint:  "/bin/sh -c 'sleep 10 && certbot certonly --webroot --webroot-path=/var/www/certbot --email pashasil-5@email.ru --agree-tos --no-eff-email -d pashasill-5.fvds.ru'"

networks:
  default: