# Generated by Django 5.2.2 on 2025-06-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('registration_address', models.CharField(max_length=255, verbose_name='Адрес регистрации')),
                ('actual_address', models.CharField(max_length=255, verbose_name='Адрес регистрации')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('activity', models.TextField(verbose_name='Основной вид деятельности')),
            ],
        ),
    ]
