# Generated by Django 5.2.2 on 2025-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycard',
            name='image',
            field=models.ImageField(blank=True, upload_to='contacts/', verbose_name='Фото'),
        ),
    ]
