# Generated by Django 5.2.2 on 2025-06-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactbackground_remove_companycard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycard',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companycard',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AlterField(
            model_name='companycard',
            name='activity',
            field=models.TextField(verbose_name='ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='companycard',
            name='actual_address',
            field=models.CharField(max_length=255, verbose_name='Фактический адрес'),
        ),
    ]
